# 作者简介 {#author}

这将是一群深度操作系统爱好者的杰作！！！

我一直致力于寻找合作者，但是我感觉现在有点迷茫。这边进度实在是慢，常常一个月写不了多少内容，可能一个月就几百字，都写不到一页内容。经常停下来。我只是想告诉别人，这个事业还在继续中。我却找不到一点点进步的身影。

现在（2017-10-29）写作进行的很困难，主要是零碎的时间很难用于整理大篇大篇的文字。还有其他繁重的任务要做，似乎不太容易写。我觉得可以分析一下困难，研究一下对策。不要再让这本书半途而废了。现在遇到的问题，负责带教，挤占了较多的时间，一时半会，他们也帮不上忙。还有两个网站的内容在整理，不可荒废。包括驾校也要报名。结婚的事情，还有一大堆。也就是有这么几件事，婚前准备，两个网站的维护，驾校考试，带教学习，完成本书第一版草稿，基本就是这么个优先级顺序，当然时刻伴随着要上班这个无法逃脱的事情。鉴于此，我认为接下来可以这样安排。婚前准备虽然优先级高，但是实际占场时间不多，如果可以快速下决定，花不了太长时间的。两个网站的维护，基本上要浪费掉很多晚上的时间。可以每天抽出两个小时的时间，弄一弄。驾校的事情，周末可以去试试，也可以在工作间隙去练练。带教学习，也是很耗费时间的，每次可能要一到两个小时，一周也就两到三次。可以跟网站维护交叉进行。完成本书第一版草稿，更是要耗费几年时间的任务。另外带教学习的就是本书，可以充分利用这个带教的事情，毕竟有徒弟可以帮着写写画画的。制定这么一个时间表，有时间里面把婚前准备的事情给结束掉，避免多次设想，带来的巨大时间浪费。每周抽出两到三天晚上带教，可以做好任务安排，每完成一章课程，作业就是帮我整理本草稿。剩下的两到三天去编写网站代码，做好维护，且不再增加新的网站或者其他任务了。驾校的事情，暂且缓一缓，找个时间去把科目一考了。

终于领结婚证了（2017-11-03），我现在觉得写作特别耗费时间，需要“ 庙算” 一下，好好规划一下，要写哪些内容。 github 的一些功能是非常值得充分利用的，比如 issue，这样可以充分利用零碎时间。半夜我坐在一个孤独的房间，又不看书，怎么可能写好这个笔记。必须边学习边做笔记，也就是写到 issue 上。不要手机整天微信、支付宝了。

（2018-12-04）工作尚可。妻子怀孕，也不能多陪伴，心有内疚。感觉很多事情一团糟，停下来，重整行装再出发。期待明天更美好吧。(2019-01-06)儿子出生，忙着带孩子，期间很忙，告诉自己，一定要坚持下来。

时间到了五一，工作家庭等等很多矛盾一下子都出来了，是时候要解决一波问题了。感觉最近的技术路线有点迷茫，有时候想学习信息安全，有时候想学习Linux运维知识，有时候想学习网站相关的一些内容。时间安排也不够合理。之前阅读了《为什么精英都是时间控》，也应该安排一下自己的写作时间了。首先根据优先级，睡觉前十五分钟记性最好，确定是每天必须听听英语的，这个不管是在家里，还是在单位，都能够实现，那就形成一个雷打不动的习惯，不改了。每周至少三个晚上，当天晚上运动一个小时，运动后，头脑更清醒，可以写作本书，或者学习其他知识两个小时，直至睡觉前了。下午午睡时间够长，在保证睡眠时间的前提下，可以睡半个小时左右。看会书，直至上班。下午多一些跑腿的工作，这个时候确实精力不是很好。上午，八点到十点，好好研究办公知道手册的内容，改版，后面时间充裕的话，可以动手写代码了。每天早上一早，每周末都要想好当天当周应做的工作。现在路线确定了，就是要好好学习网站技术，Linux运维技术，服务当前工作。

2019年五月下旬，随着美国总统对华为的“禁令”，网上相关信息铺天盖地，有幸拜读《下一个倒下的会不会是华为》，提到的一些观点，还是值得参考的。初步计划是跟着大神贡献代码，等有条件了自己好好写代码。

2019年八月，基本定下来学习[mattermost](https://github.com/mattermost)了，好好学习别人的代码，再难也要坚持。其他的想法都放弃。

在《论持久战》中，毛泽东就“很多人对于官兵关系、军民关系弄不好，以为是方法不对”的片面认识，明确讲到：“我总告诉他们是根本态度（或根本宗旨）问题，这态度就是尊重士兵和尊重人民。从这态度出发，于是有各种的政策、方法、方式。离了这态度，政策、方法、方式也一定是错的，官兵之间、军民之间的关系便决然弄不好。”“那些认为不是根本态度问题而是技术问题的人，实在是想错了，应该加以改正才对。”（《毛泽东选集》第 2卷，人民出版社 1991年版，第 512页。)

2019年十二月，当了一年的工具管理主任，跟各方打交道，发现综合素质里很缺乏管理经验啊。管理这么些错综复杂的关系，其实也不是很复杂，感受最深的一点是一定要把法规制度学好，法规制度没学好让自己吃了不少亏。所以，既要有软的一面也要有硬的一面，可以和蔼可亲，也要有制度纪律来管理约束。关于要不要干掉不服管的下属，想过“害群之马”，也想过“为渊驱鱼”，况且手里的权力还没有大到随意换人的地步，换人也是有代价的，况且这些赶人的手段是最终手段，不能常用，就像刑罚里的死刑，不能随便就用的，想一想手段也不止这些办法，中间还是有很多方法可以做的。所谓“斗米养恩，石米养仇”，没有纪律做后盾，和蔼可亲就变成了软弱可欺。带孩子也类似，太宠溺了，不仅是在害孩子，也是在害自己。老子说”天地不仁，以万物为刍狗“。大自然是残酷的，自己也曾感慨过”世界的本质是限制“，万事万物都有自己的规律和作风，这宇宙不是哪个人的宇宙，该立起来的还是要立起来，三十而立，自己也是一方天地。再回首看毛爷爷的那些话“关系搞不好，是根本态度问题”，是应该反思一下的。

参考网页的一些好友大神，比如[@duanyao](https://bbs.deepin.org/home.php?mod=space&uid=30023&do=thread&view=me&from=space)，另外直接写作的身边人：黄煌、贺鹏飞、董春柏、邱鹏飞、高洪亮，还有抱歉没来得及全部写在这里，以后慢慢添加，在此表示感谢。
