\mainmatter
\pagestyle{main}

\partquote{春江水暖鸭先知}{苏轼}
\partintro{
这里需要写点啥的。
}
# (PART) Linux 入门 {#part:intro -}

# GNU/Linux 操作系统简介 {#linux-intro}

通过阅读本章，你将会了解到以下几项内容。
- Linux 使用范围。
- Linux 发展简史以及 GPL 协议。
- 如何学习 Linux。

## GNU/Linux 使用范围

有人说， Linux\index{Linux} 作为服务器操作系统，在市场上占有绝对优势，在超级计算机前 500 名中更是占有垄断地位。好吧，这些都不是我们关心的事情。我们关心的是 Linux 能在我用着方便的领域能占多大范围。
**如果你是程序员。**你可以用它方便的写代码，并很容易调试。有功能异常强大的终端，供你跟整个世界沟通。方便你写文档。当然也可以用它来听听音乐，看看电影啦。
**如果你只是在家里使用。**比如趣味性，听听音乐，看看电影，这些都是可以办得到的。那办公呢，搜狗拼音输入法，赫然在列，金山的 WPS 办公套件也是能满足你基本需求的。那 QQ 呢，这个也是必须有的，能不能告诉你，在深度 Linux 已经实现视频聊天了呢。那打游戏呢？很不幸的告诉你，Linux 操作系统下能玩的游戏真心不多，你如果特别喜欢玩游戏，还是不建议你在 Linux 上玩啦。
**如果你是办公室汉字作业者。**那办公呢，搜狗拼音输入法，赫然在列，金山的 WPS 办公套件也是能满足你基本需求的。那 QQ 呢，这个也是必须有的，能不能告诉你，在深度 Linux 已经实现视频聊天了呢。当然还有很多特殊的办公软件在 Linux 下没有可用的版本。比如 photo shop， autoCAD 等。不过也有对应的 Linux 开源版本。

另外 Linux 桌面操作系统，稳定性不是很高，但也没有 Windows 下全家桶系列乱弹窗的软件。如果你对桌面清洁有特殊爱好，且 Linux 能满足你日常生活需要，不妨来试试它啦。

## Linux 是什么

什么？其实他就是一个电脑操作系统啦。那操作系统是啥，那我也不知道啦，这个你可以百度一下，简单的说就是方便你操作电脑的一个软件系统。关于 Linux 有啥发展历史，以及跟 GPL 协议有啥关系。这些网上都有铺天盖地的介绍，本书就不介绍啦。不过还是要介绍两个人，一位是 GNU 的老大[Richard Stallman](http://www.stallman.org/)，一位是 Linux 的老大 [Linus](https://en.wikipedia.org/wiki/Linus_Torvalds)。

## Linux 发行版的出现



## 如何提高自己的 Linux 技术

好好学习，天天向上。毛爷爷如是说。有人说学习 Linux 要不断的折腾。
