# shell 用法简介 {#shell}

## 引言

作为普通人，使用电脑除了窗口图形界面外，还有个叫终端的字符界面。Linux 中通过在终端敲击字符跟电脑交互，这玩意就叫做 shell，并且相比图形界面（Graphic User Interfaces, GUI），通常 shell 功能更加强大。

深度系统默认采用的 shell 是 `bash`（Bourne Again Shell），继承兼容于 UNIX 早期的 Bourne shell （作者：Stephen Bourne, 命令名为 `sh`）。曾经有一段时间深度默认 shell 是 `zsh`，经群众投票又改回 `bash`了，其实那次投票是我发起的。

除此之外，类 UNIX 系统还有其他的一些 shell,比如 `ksh`,`csh`,`tcsh`，有兴趣的可以查相关资料，这里不说了。

## 用 shell 有啥好处？

为了装吗？不见得。

刚接触 Linux 桌面发行版的时候，按着教材说的，就在学习终端哦。遇到糟糕的 Linux 图形界面卡住了、死机啦，不得不网上搜索解决方案，能不用终端 shell 吗？作为小白，遇到各种各样的问题，查询询问的结果，大神的建议，也多半是在 shell 下解决啊，这叫不得不用。

后来慢慢脱离低级小白，开始喜欢上终端远程连接其他 Linux 电脑，享受这种快捷方便的操作。再后来终端下用 vim 写代码，键盘翻飞，似乎成为了一种享受。

再后来，开始接管一些服务器，开始学习计算机安全知识，似乎更离不开了 shell 了。似乎儿时那种黑客的感觉，只有通过 shell 才可以实现哦。

其实 Windows 下也有 DOS 和 CMD 这类字符操作界面，不过功能弱爆了， powershell 可能功能强大一些，有兴趣的可以查相关资料，这里不说了。

## 深度操作系统下 shell 简介

按照《Linux Bible》的说法，有三种方式打开 shell 操作界面，分别叫shell提示符（shell prompt），终端窗口（Terminal window），和虚拟控制台（virtual console）。我感觉深度操作系统就后面两种。

深度操作系统登录后，进入桌面，按下 `Ctrl + Alt + T` 或者 `F4` 会弹出深度终端窗口，这个软件在第三章已经作了介绍。可用于 shell 练习。对于虚拟控制台，可以通过按下 `Ctrl + Alt + Fi` 其中 Fi 表示 F1,F2,...,F6。分别弹出六个虚拟控制台，详情见后面叙述。


