# 进程管理 {#chap:manager-process}

通过阅读本章，你将会了解到以下几项内容。

- 显示进程
- 进程前后台切换
- 对进程的生杀予夺

## 何谓进程

参考网页：

- http://www.cnblogs.com/xiaojiang1025/p/6021049.html
- https://www.cnblogs.com/vinozly/p/5585683.html
- https://blog.csdn.net/hq_buddhist/article/details/51233808
- https://linux.cn/article-8451-1.html

Linux 是一个多用户多任务的操作系统。多用户是指多个用户可以在同一时间使用计算机系统；多任务是指Linux可以同时执行几个任务，它可以在还未执行完一个任务时又执行另一项任务。

进程是指正在执行的程序；是程序正在运行的一个实例。它由程序指令，和从文件、其它程序中读取的数据或系统用户的输入组成。进程的一个比较正式的定义是∶在自身的虚拟地址空间运行的一个单独的程序。进程与程序是有区别的，进程不是程序，虽然它由程序产生。程序只是一个静态的指令集合，不占系统的运行资源；而进程是一个随时都可能发生变化的、动态的、使用系统运行资源的程序。而且一个程序可以启动多个进程。

进程具有如下特定：

1. 相应的程序+CPU上下文+一组系统资源
1. 动态性, 独立性, 并发性
1. 一个CPU，任何时刻最多只能有一个进程去使用它

PID 呢？

进程的调用资源权限，user,group,等

进程的被管理权限

*/proc* 呢？

## 深度系统监视器

## 命令方式查看进程

## 进程的分类

在 Linux 中主要有两种类型的进程：

    前台进程（也称为交互式进程） - 这些进程由终端会话初始化和控制。换句话说，需要有一个连接到系统中的用户来启动这样的进程；它们不是作为系统功能/服务的一部分自动启动。
    后台进程（也称为非交互式/自动进程） - 这些进程没有连接到终端；它们不需要任何用户输入。

什么是守护进程

这是后台进程的特殊类型，它们在系统启动时启动，并作为服务一直运行；它们不会死亡。它们自发地作为系统任务启动（作为服务运行）。但是，它们能被用户通过 init 进程控制。

## 对进程的操作

### 进程的状态

参考网页：

- https://blog.csdn.net/sdkdlwk/article/details/65938204