# 深度系统安装 {#chap:deepin-install}

本章讲介绍如何从优盘、光盘和硬盘安装深度操作系统，以及 LiveCD 模式简介。

参考网页：

+ https://bbs.deepin.org/forum.php?mod=viewthread&tid=135051
+ https://wiki.deepin.org/index.php?title=%E5%8E%9F%E7%94%9F%E5%AE%89%E8%A3%85

对以上作者表示感谢。

## UEFI 和 legacy BIOS 区别和联系

参考网页：

+ https://baike.baidu.com/item/UEFI/3556240?fr=aladdin

有些电脑过于老旧，不支持 UEFI 模式，或者没能设置启动（boot）为 UEFI 模式，导致安装失败。

## 优盘安装{#deepin-install:upan-install}

一般电脑都是可以安装的，当然也存在安装失败的情况，对于遇到困难的用户，可以百度或者谷歌怎么解决。这里只叙述需要注意的问题。现在的电脑一般都带 USB 接口，支持优盘安装的。USB 接口，现有 1.0,2.0,3.0 等各种版本，更多了解可以参考[百度百科](https://baike.baidu.com/item/USB%E6%8E%A5%E5%8F%A3/493294?fr=aladdin)。在采用优盘安装的时候，需要事先检查你电脑的 USB 接口是否工作正常，之前帮一同事安装系统，折腾了一上午才发现 USB 接口是坏的。更有甚者，部分电脑的 USB 3.0 的接口，可能不支持优盘安装，这个都是需要特别注意的。

接下来是制作优盘。你可以采用 windows 或者已经安装的深度操作系统制作优盘，当然对优盘大小等还是有限制的，一般大于或等于 8G 为宜。

### 第一步下载并校验 deepin.iso 文件

本节转载自[深度维基百科](https://wiki.deepin.org/index.php?title=%E5%8E%9F%E7%94%9F%E5%AE%89%E8%A3%85)，有改动。对前人的辛勤工作，表示感谢。

**官方镜像**

访问 deepin 社区[下载页面](https://www.deepin.org/download/) ，下载深度操作系统系统最新版本的镜像文件（以便您能够体验到最新特性）。（据我本人的经验，如果你没有百度 VIP 账号，不建议从百度网盘下载。国内从官网或者 [sourceforge](https://sourceforge.net/projects/deepin/)相对快一点，也不是绝对的，可以根据实际情况选用不同的下载点）注意：为了更加专注系统的发展，deepin 15.4及后续版本将不再提供32位官方iso镜像，如需获取和技术支持，请发送邮件到[support@deepin.org](mailto:support@deepin.org)。

**MD5校验**

下载深度操作系统镜像完成后，需要对其进行校验，非官方或不完整的镜像将不能用于深度操作系统的安装：

- Windows系统：下载Hash软件 ，校验您下载的镜像的MD5值与下载页面 提供的 MD5 值是否一致。( MD5 值在立即下载按钮下方)
- Linux系统：在对应的镜像文件下，打开终端，执行md5sum deepin-xxx.iso命令，请确认下载的镜像的 MD5 值与下载页面提供的 MD5 值是否一致。( MD5 值在立即下载按钮下方)。说明：deepin-xxx.iso即为下载的系统镜像文件名，可使用 Tab 键自动补全文件名。

## 光盘安装

这个比较少见了，不排除也有人这么干，比如一些涉密场所等。基本是刻盘，然后拿到需要安装的电脑上，重启电脑，进入 UEFI 启动菜单，也可能需要设置BIOS等才可以进入 UEFI启动菜单，选择从光驱启动，通常是含有DVD字样的为光驱启动。接下来从略。

## 旧版Deepin下的硬盘安装

参考网页：

- https://bbs.deepin.org/forum.php?mod=viewthread&tid=179215

本次讲述如何在旧版Deepin 2014上硬盘安装当前最新的Deepin 15.11 版本。

转载，有改动，已获[许可](https://bbs.deepin.org/forum.php?mod=redirect&goto=findpost&ptid=179215&pid=615712)

当前没有可用U盘，但是旧电脑上安装了双系统，WinXP 和 Deepin 2014，庆幸的是电脑支持64位操作系统，且只有一个机械硬盘，做了三个盘，C盘，D盘和旧版Deepin2014安装的E盘。当前无法使用网络更新到最新的 Deepin 15.11 版本。只能下载15.11的 iso文件。下载的时候发现，到[社区iso仓库](https://www.deepin.org/mirrors/releases/)的阿里云，速度果然是大厂的速度，贼快，特别兴奋。

所谓硬盘安装，就是将安装盘的 iso 文件置于某个硬盘分区上，然后引导到安装盘，将系统安装在另一个硬盘分区上的方法。硬盘安装不需要光驱或者U盘，有时候比较省事儿。步骤如下，如无特别说明，前期一直运行于旧版Deepin 2014操作系统下：

1. 将安装盘的 iso 文件（如 *deepin-15.11-amd64.iso* ）置于某个硬盘分区的根目录上，这个分区的格式可以是FAT、NTFS、Ext2/3/4 之一。不在根目录或者iso的文件名不同也行，但后面的*grub.cfg*要相应修改。其他分区格式可能也行，我没试过。注意，你的 deepin 系统就不能安装到 iso 所在的分区了，得准备另一个分区。比如本人放在了 */media/litianci/data/*磁盘根目录下，运行`df -h .`得知该设备为 */dev/sda5*，在WinXP里，是D盘。当前旧版Deepin下该ISO文件为*/media/litianci/data/deepin-15.11-amd64.iso* 文件，

2. 修改 */boot/grub/grub.cfg* 文件。查找`menuentry`，把下面的代码仿照原有的`menuentry`格式，插入到该文件，

```
    menuentry 'deepin install' {
        set root=(hd0,5)
        set isofile="/deepin-15.11-amd64.iso"
        loopback loop $isofile
        linux (loop)/live/vmlinuz.efi  boot=live union=overlay username=user quiet  live-config noprompt noeject findiso=$isofile locales=zh_CN.UTF-8
        initrd (loop)/live/initrd.lz
    }
```

3. 保存重启机器，进入 UEFI 启动菜单（按照机型和BIOS的不同，可能是按F12、F2、F9、ESC等，可能还要先在BIOS里设置启动等待时间大于0），应该会显示 'deepin install' 的 grub 菜单项，再选中即可启动 iso，开始安装 deepin 。接下来基本是傻瓜式安装，这里不叙述了。

## Win10 下双硬盘的安装

这里讲述的是当前比较新的电脑，一般配置一个固态硬盘和一块机械硬盘。本文介绍如何把Deepin 15.11 安装到固态硬盘里。这次试验的电脑固态硬盘 500G，单独为一个C盘，安装了Windows 10，仅占用了较小一部分，分出 100G 的E盘后足够安装 Linux Deepin。具体步骤如下：

### 下载几个软件

deepin-15.11-amd64.iso 是不用说，必须下载的。另外还有个 [diskgenius分区工具](http://www.diskgenius.cn/)，用于把固态硬盘分出 100G来。

### 固态硬盘分区

安装 diskgenius，本次是从官网下载的免费版，分区是免费的。具体分区方法见[网上](http://www.diskgenius.cn/help/partspliting.php)，这里从略。最终 500G 的C盘被分为 400G的C盘和100G的空的E盘。另外1T的机械硬盘为D盘，具体怎么分，根据个人爱好吧，这里仅仅为了安装Deepin的需要而分区。

### 使用优盘制作启动盘

这个参考上面\@ref(deepin-install:upan-install)。

### 设置磁盘序列模式为 AHCI

双显卡电脑的安装\index{双显卡电脑}，安装系统前，进入电脑的BIOS界面，选择到Configuration页面，将SATA Controller Mode选项中的Intel RST Premium，改成AHCI。修改之后，按下F10键保存，选择YES保存并退出。然后可以在通过引导进入安装系统的界面，可以正常找到固态硬盘，然后安装操作系统了。

## 安装常见问题

参考网页：

+ https://bbs.deepin.org/forum.php?mod=viewthread&tid=146222
+ https://bbs.deepin.org/forum.php?mod=viewthread&tid=146224

基本全文转载，有改动。已获[许可](https://bbs.deepin.org/forum.php?mod=viewthread&tid=146224&page=1#pid384937)。

### 开机提示没有GRUB的解决办法

可直接查看：这里，下面我把我遇到问题的核心操作整理出来。

#### 有单独boot分区时操作方法 （你有专门为boot分区的的情况，比如说我就有）


```bash
ls                 #  应该像这样  (hd0),(hd0,msdos3),(hd0,msdos2),(hd0,msdos1)
ls (hd0,x)         # 盲查，这里x跟比如msdos2中的2一致，查看哪个是ext[x]格式（比如ext2），如果你知道，可直接下一指令,比如我的是(hd0,4)
ls (hd0,x)/grub    # 查哪个是否有包含文件名有i386的文件，如果不包含，那可能系统没装完整，boot区缺少内容，最直接办法就是重装（注意设置好BIOS）
set root=(hd0,x)   # 把启动目录设置成上一行指令已确认的x,比如(hd0,4）
set prefix=/grub   # 因为 grub目录在boot分区，并且上一指令已经设置了boot分区地址，现在已经在boot分区（文件夹）内，所以这里可以直接这样做
insmod normal      # 上面步骤都没有提示的话，说明没毛病，接着这样做。
normal             # 如果上面都正常，这条命令输入后应该可以进入引导界面了吧
```

上面从ls (hd0,x)/grub就没有发现包含文件名有i386的文件，那就得注意了，可能系统没装完整，boot区缺少内容，这种情况估计只能重装了，这情况我在装Ubuntu系列系统（Ubuntu,Kubuntu, elementary, linux mint等我都装过）时遇到过，原因是你的win用的legacy模式安装，而Ubuntu却使用UEFI模式安装，这个安装过程中有提示，如果它提示说是否强制UEFI，那你就就别强制了，因为肯定出错，导致boot区肯定没引导文件，重新设置BIOS才是正确做法。以下总结几种情况：

1. BIOS中只有legacy模式

这种情况就好办了，直接把USB启动项调到第一个然后插入U盘重启就好了，系统会先从U盘启动。

2. BIOS中有legacy和UEFI（应该现在大部分新机是这个）

这种情况对于deepin来说很简单，要不设置成UEFI first， 要不直接从boot menu的UEFI项启动即可，如果使用legacy可能会进不了安装界面，反正我的是这样，如果不嫌麻烦，你也可以试试。

而对于Ubuntu系列来说（如果你想装的话可以看看），这种情况就得注意了，最好设置成legacy first，或者直接从boot menu的USB...项启动（一般包含一个UEFI开头的usb和一个usb），这时候有两种情况，要么可以进入安装界面（欣喜），要么提示错误说 root file system not found。。之类的（大概这样，记不太请了），那么出现这样的问题最直接的原因可能就是BIOS设置有问题（起初我怀疑是启动盘制作问题，其实不是），那么你需要重新设置BIOS，最好先恢复默认，再逐个设置，确保没有误操作。值得注意的是，如果你的win装的是legacy，你非要强制UEFI，那么你的之后win是无法启动的，直到你安装成功后在Ubuntu recovery mod中 使用grub重新引导才可以（也有可能不可以，看你帅不帅了）。

3. 安装成功后通过win引导选项无法进入win问题修复。

进入deepin recovery模式（advance模式），通过grub重新引导，系统会重新生成引导，如果之前的有毛病，那么这里可能会有所修复。退出重启，这里要说下recovery模式下的问题，这可能是个bug，导致该模式非常难用，我用过Ubuntu系列的，做的很好，响应很即时没啥毛病，但是deepin，基本上你在执行某个选项后就很有可能回不来了，即使回来了也可能不能再选择其他选项，要想退出只能靠电源键了（可能是个人情况）。重启后如果依然没办法进入win，别着急，多尝试几次，如果还没办法，先进如deepin用着再说，下次再尝试进入win的时候很大几率是可以进去的，如果进入了，那么以后就一直可以了，这个我也不知道为什么。


#### 无单独boot分区时操作方法 （你没单独分区就没有）

```bash
ls                    # 应该像这样  (hd0),(hd0,msdos3),(hd0,msdos2),(hd0,msdos1)
ls (hd0,x)            # 盲查，这里x跟比如msdos2中的2一致，查看哪个是ext[x]格式（比如ext2），如果你知道，可直接下一指令,比如我的是(hd0,4)   
ls (hd0,x)/boot/grub  # 查哪个是否有包含文件名有i386的文件，如果不包含，那可能系统没装完整，boot区缺少内容，最直接办法就是重装（注意设置好BIOS）
set root=(hd0,x)/boot # 把启动目录设置成上一行指令已确认的x,比如(hd0,4）   
set prefix=/grub        
insmod normal         # 上面步骤都没有提示的话，说明没毛病，接着这样做。
normal                # 如果上面都正常，这条命令输入后应该可以进入引导界面了吧
```

#### 登录界面死循环，以及登陆后桌面不显示的可能原因及补救方法

登录界面死循环这个问题问题我是在使用ubuntu时遇到的，可能deepin也会存在，在这大伙预防预防；而登陆后桌面挂了（黑屏但是鼠标、文件管理起可用）的问题，我之前求助过，这里和这里这里，感谢各位的热心帮助，可能刚开始不太习惯一些操作，也没遇到过这些问题，所以总有点傻傻的。关于解决这个问题，我是再次回装ubuntu时遇到的，然后在Ubuntu解决后回到deepin，发现有效果，这里总结一下。

登录时死循环和登录后桌面不启动可能是一个问题，就我的情况看来，是自定义的配置有问题导致的，为什么呢？先说几个常识吧，一般来说，在终端中的用户名是高亮显示的，这个有注意到吧，好，那么如果某一指令让它变暗了，也就是说不高亮了，那么，这个指令肯定有问题，可能并非指令本身的问题，而是指令让系统某一文件发生改变而导致有错误异常，接着，你输入的所有指令都可能提示无法找到，比如说sudo、cd，这不可能找不到是吧。那么，出现这种情况你就得注意了，因为你之前的指令、修改的内容可能让你的系统崩溃，具体什么现象，得看你修改的是系统的什么文件，轻则某项功能无法使用，重则无法再次启动，虽然你当前可能不会有什么异常情况。

那么如果你忽略了上面所说的问题，就可能导致错误，这还真跟deepin无关，都是自己的问题，所以遇到这样的问题别老说deepin有bug，先想想是不是自己哪里操作错了。

就我的情况看，配置JDK环境对于每个跟java打交道的人来说都是必备常识，但是这一小门槛还真郁闷了不少人，有时你的操作并没问题，但是效果却不如所愿。比方说我这次，登录时死循环和登录后桌面不启动的问题就来源于这里，我用

```bash
$ sudo gedit /etc/profile
```

打开profile添加配置JDK环境，没毛病，常规操作，配置好后

```bash
$ sudo source /etc/profile
```

立即生效，也没毛病，常规操作。但是并非如此， 用户名的高亮变暗了，奇怪吧，但是我输入java测试，有提示输出，java -version也没毛病老铁，于是就不管了，继续做自己的事，但是有点不放心，于是重启系统。登录后的问题结果在Ubuntu和deepin中表现不太一样（可能是个例），比如Ubuntu中是登录界面死循环，而deepin是登录后桌面不启动。至此到了解决问题的关键环节,下面说说我的解决办法，其实很简单，就有点像打字打错了，你撤销操作一样，但是对于这种已经被保存的文件而言，你需要先找到他，然后删除因你的操作而添加的内容。 具体做法如下：

1. 在登录界面  快捷键 ctrl + alt + f1,  这个会进入一个黑屏界面，只有一个_光标，没关系，继续 ctrl + alt + f2, 进入终端， 其实就是没有界面的linux系统，在里面你可以进行所有终端能完成的操作，除了开启界面软件外。

2. 输入命令操作，当然，这里就需要你比较熟悉linux命令了，如果不太会也没关系，网上有很多资料，也有很多热心人提供解决方案，比如说deepin社区。

针对我的问题，当然就简单了，  sudo vi /etc/profile 打开proifile配置文件，删除我添加的jdk环境变量，保存，OK，这就完事了，没那么难吧，当然，有很多更加复杂的问题，这里我也没遇到过，但是思路是一致 的（误操作 -->异常 ---> 撤销操作 -->  异常解除 ），比方说有的老铁安装了专用显卡驱动导致桌面异常或者无法启动桌面，那么你要做的就是卸载你装的专用驱动，换成开源驱动，问题解决。 没毛病吧老铁。

针对JDK配置，当然，但凡跟改系统文件相关的操作都最好先备份，再修改，最好寻找可替代的可命令完成的解决方法，因为手动编辑很可能出现问题。那么可以如下操作:

```bash
$ sudo apt-add-repository ppa:webupd8team/java
$ sudo apt-get update
$ sudo apt-get install oracle-java8-installer
```

当然在deepin中执行上面命令会提示apt-add-repository 不存在，没关系，我们先执行下面命令安装相关依赖：

```bash
$ sudo apt-get install python-software-properties
$ sudo apt-get install software-properties-common
```

至此，我的问题就解决了，deepin做开发是没毛病的，暂时从响应速度上来看，比Ubuntu好些，看具体需求吧。

3. 总结

怎么说呢，既然你选择使用linux，deepin也好还是其他，操作前请记住一点，一定要清楚你在做什么，可以不管操作会带来什么后果，但是你得清楚你的操作了什么，这对后续补救非常有利，别问我怎么知道，都是浪费的时间换来的血泪教训，希望对老铁门有所帮助，如果有啥错误或这老铁们有啥补充的，请在留言中补充，为了帮助（留住）更多想要使用deepin的人，把我们遇到的现实问题及解决办法都总结出来是很好的办法。

## Live 模式

在正式安装系统之前，可以体验一下该操作系统如何。或者在系统崩溃了使用Live模式修复系统。建议添加live模式的详细介绍。

另外深度自带**深度备份还原工具**，可以在深度商店搜索下载。

## 苹果电脑上安装双系统 MacOS + Deepin

前面电脑分区导致硬盘容量缺失，应该是 MacOS 系统的问题，通过[CSDN一篇博客](https://blog.csdn.net/pku_Coder/article/details/76864653)的方法，顺利解决了硬盘问题。

其实，苹果系统存在的几个问题，比如硬盘容量丢失，或者无法连接网络等。这些通过图形界面操作异常的问题，常常可以通过命令行解决。


> 用磁盘工具直接分区，随便分个大小，格式选择默认的os x扩展，然后点击分区，过一会 会显示分区成功，这时候你看你原来丢失的100g回来了，在你刚刚新分的盘里了。这时候点击减号把这个分区抹去就行了~
>
> --- [CSDN博主PKU_CXK](https://blog.csdn.net/pku_Coder/article/details/76864653)

参考网页：

- 