# 软件安装 {#chap:software-install}

这里会介绍如下几种安装方式，

- 源码安装
- 软件包安装
  - 直接双击安装
  - apt 安装
  - dpkg 安装
  - run 类型的文件安装
  - 其他软件安装，比如 `you-get` 的安装
- 软件包管理软件安装
  - 应用商店
- 字体的安装
- 输入法的安装
- iso 文件安装
- pandoc 安装
- 编译内核

并重点介绍对**deb**安装失败的修复问题。

## 源码安装

源码安装属于Linux系统早期软件安装的常用方式，优点是较大的自由度，可以针对性的优化，源码比较新等；缺点是编译比较耗时，难度也较大，可能对部分软件的依赖性比较强。对于具有一定技术能力，想尝鲜的或者急需某些功能的用户，可以根据那些提供源码的特定软件，按照编译说明，试着编译。也是一种别样的乐趣。

## 软件包安装

随着技术的发展，为了满足“人们日益增长的物质文化的需求”，把应用程序的二进制文件、配置文档和帮助文档等按照一定的规则打包在一个文件里，用户只需要使用软件包管理器来安装卸载升级查询软件即可。该方法的优点是通用性好、方便普及，缺点是可能不会针对平台硬件优化，各软件包相互依赖比较错综复杂等。常见的软件包格式有RPM、DEB等。

## 深度商店之WPS办公套件的安装

当然WPS办公套件是深度操作系统自带的，这里提到他有点打广告的意思。其实很多常用软件都可以在深度商店找到的。

## npm 软件的安装

这里以 `you-get` 软件为例，介绍 npm 软件的安装方式。

## veil 软件安装

其他发行版可以直接用 `apt-get` 直接安装的，比如 veil,

```bash
$ sudo apt-get install veil
```

在 Kali Linux 就可以直接运行，但是在深度操作系统下就无法下载，这个时候不妨网上搜索一下，加入私有源。当然最好的是搜到这个软件的官网，比如 `veil` 的官网：[https://github.com/Veil-Framework/Veil](https://github.com/Veil-Framework/Veil)，按照原作者的方法安装，也是不错的。

```bash
$ sudo apt-get -y install git
$ git clone https://github.com/Veil-Framework/Veil.git
$ cd Veil/
$ cd setup
$ sudo ./setup.sh -c
```

这样一路点击确认下来，慢慢等待，就可以成功安装 `veil` 了，当然还需要对 *setup.sh* 文件检测操作系统的代码改一改，让他支持 `deepin`。详情见[pull request](https://github.com/Veil-Framework/Veil/pull/130)。用方法有所变样。

也可以到 debian [软件包库](http://www.debian.org/distrib/packages)去搜索，相关的软件包，选择合适的版本安装。不过 `veil` 没有对应的 deb 包。这是一个比较庞大的软件，估计也不会有一个小的包。

## dpkg 安装

## 其他安装方式

很多软件，由于依赖或者其他原因，安装起来特别费劲，对于初学者，不啻于一场灾难。有好事者，就提供了各种一键安装包。下面介绍两个，限于本人水平，也就只知道这俩，有同仁知道更多的谢谢发表评论。

### bitnami

官网：https://bitnami.com/stacks

提供一键安装软件包，或者虚拟机级别文件等。有需要的可以去查询，肯定有你所需要的。比如 gitlab，OwnCloud 等等

### turnkeylinux

官网：https://www.turnkeylinux.org/

对于常见的 gitlab,lampp等提供虚拟机安装包，可以尽情享受快捷。

另外，我常用的 xampp 一键安装包，却是从其他网站上下载的。如果你安装一个软件特别费劲，（不包含无法破解软件的哦）不妨试试搜索一下 “xxx 一键安装包”,看看有没有其他人已经帮你解决这个问题了。

## you-get 软件的安装

参考网页：

+ https://github.com/soimort/you-get
+ 

根据 you-get [源码网站](https://github.com/soimort/you-get)的提示，在 deepin 下，用如下命令安装，较为合适。

```bash
$ sudo pip3 install you-get
```

但是，你可能会发现，自己的电脑没有安装 `pip3` 软件。试着 `sudo apt-get install pip3` 也不存在这个软件包啊。接着百度 `how to install pip3`，找到一大堆页码。参考[这个](http://ask.xmodulo.com/install-pip-linux.html)，如下命令安装。

```bash
$ sudo apt-get install python3-pip python3-dev build-essential
```

这样就安装好了 `pip3`，我的理解，`pip3` 就是 `python3-pip` 的意思，不知此解对不对。那么接下来安装 `you-get` 就容易多啦。

```bash
$ sudo pip3 install you-get
```

如果需要更新 `you-get`，可以如下。

```bash
$ sudo pip3 install --upgrade you-get
```

对于 `you-get` 如何使用，这里就不赘述啦。详见[官网说明](https://github.com/soimort/you-get)。

## 字体的安装

有些书籍的制作需要特殊的字体，在 Windows、Mac 下安装字体比较简单，在 Deepin 下安装字体同样很简单。参考[这里](https://github.com/weijianwen/SJTUThesis/blob/master/tex/app_setup.tex)，

下载需要的字体，下面以安装交大论文需要的字体为例，网上下好需要的[字体](http://download.csdn.net/download/bubifengyun/9695994)，解压缩后，双击安装即可，也可以仿照上面[网页](https://github.com/weijianwen/SJTUThesis/blob/master/tex/app_setup.tex)提供的方式安装。

```bash
$ mkdir ~/.fonts
$ cp *.ttf ~/.fonts				# 当前用户可用新字体
$ sudo cp *.ttf /usr/share/fonts/local/	# 所有用户可以使用新字体
$ sudo fc-cache -f
```

**解释**
- `cp *.ttf ~/.fonts` 的 `*.tff` 表示你下载的那些字体，需要你修改为对应字体的路径。

## 输入法的安装

这里以搜狗输入法为例，讲解怎么在没有安装搜狗输入法的 Linux 桌面发行版上安装 搜狗输入法，其实深度操作系统自带搜狗输入法的。当然第一步百度搜索了，搜索到搜狗输入法的 Linux 专用版[网站](http://pinyin.sogou.com/linux/)，上面网址如果不对，请继续搜索，毕竟某搜索网址广告比较厉害，不一定就第一时间提供有用的答案。进入官网，下载对应 *.deb 文件，使用命令

```bash
$ sudo dpkg -i /path/to/***.deb
```

就可以安装了。本来这个输入法安装应该放在上面的，但是考虑到很多人找不到怎么安装，特来说一下。深度操作系统下，可以直接双击下载的 **.deb 安装包的，一会就会自动安装完。不过汉语简体版的深度操作系统已经自带了该输入法。

## wireshark 的安装

包括`k3b`光盘刻录、`wireshark`网络抓包等软件，运行需要相关权限，虽然安装简单，但是安装后还需要配置权限。

## 投屏软件 scrcpy 的安装{#chap:software-install:scrcpy}

深度自带无线投屏的，见\@ref(deepin-presentation-assistant)节介绍，但是播放视频的时候会比较卡。这里介绍的scrcpy相对流畅，顺便介绍一种snap的安装方式。

参考网页：

- https://bbs.deepin.org/forum.php?mod=viewthread&tid=178520&extra=&page=1
- https://snapcraft.io/docs/installing-snap-on-deepin
- https://github.com/Genymobile/scrcpy
- https://snapcraft.io/scrcpy
- https://gitee.com/mirrors/scrcpy

### 第一种安装方法

问题太多安装失败，跳过。

```bash
$ sudo apt update
$ sudo apt install snapd
$ sudo snap install scrcpy
$ sudo reboot
```

使用方法，由于上述`snap`文件下载太慢了，源码在[码云有镜像](https://gitee.com/mirrors/scrcpy)，`snap`我在CSDN做了个备份。欢迎下载，改用下面方式即可安装完成。

```bash
$ sudo apt update
$ sudo apt install snapd
$ sudo snap install --dangerous scrcpy-snap/*
```

### 第二种安装方法

在这个之前，还需要提前安装 [`adb`](https://developer.android.com/studio/releases/platform-tools.html)，下载解压缩在 */opt/android-platform-tools/*文件夹，并创建adb的超链接。

```bash
$ wget https://dl.google.com/android/repository/platform-tools_r29.0.2-linux.zip
$ unzip platform-tools_r29.0.2-linux.zip
$ sudo cp -r platform-tools /opt/android-platform-tools
$ sudo ln -s /opt/android-platform-tools/adb /usr/local/bin/
```

后面继续安装，

```bash
# runtime dependencies
$ sudo apt install ffmpeg libsdl2-2.0.0

# client build dependencies
$ sudo apt install make gcc pkg-config meson ninja-build \
    libavcodec-dev libavformat-dev libavutil-dev \
    libsdl2-dev

# server build dependencies
$ sudo apt install openjdk-8-jdk

# 下载最新源码保存为 scrcpy.zip
# wget https://gitee.com/mirrors/scrcpy/repository/archive/v1.10?format=zip -O scrcpy.zip
# unzip scrcpy.zip

# 其实也可直接使用 git clone 复制
$ git clone https://gitee.com/mirrors/scrcpy.git
$ cd scrcpy
$ wget https://github.com/Genymobile/scrcpy/releases/download/v1.10/scrcpy-server-v1.10.jar \
 -O scrcpy-server.jar
$ meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=scrcpy-server.jar
$ cd x
$ ninja
$ sudo ninja install
```

### 使用方法

数据线连上手机，弹出窗口里选择打开USB调试，在电脑终端输入

```bash
$ scrcpy -f # 全屏显示，更多用法请查看官网
```

可以顺滑的享受播放视频了。而且支持鼠标点击和键盘操作，貌似输入法的键盘操作还不是很协调。确实比深度屏幕助手快多了，但是使用中还发现有可能导致电脑CPU狂飙，这个要小心了。可以使用如下命令强制让他熄火。

```bash
$ sudo killall -9 scrcpy # 强制关闭scrcpy
```

如果全屏，找[不到退出按钮](https://bbs.deepin.org/forum.php?mod=viewthread&tid=178520&page=2#pid615115)时，你可以按下`<Super>+D`键，或者`Alt+<tab>`键，切换一下窗口就出来了。

