# Linux 安全基础知识 {#chap:basic-security}

通过阅读本章，你将会了解到以下几项内容。

- 深度系统如何跟Windows系统共享文件、打印机；
- bash进行判断和简单数学计算
- bash 的流程结构
- 实现把UC视频缓存变为普通视频文件的脚本

安全是Linux系统的重要组成部分，也是Linux系统使用时的重要注意事项。毛泽东军事思想告诉我们，决定战争胜利最重要的因素是人，决定系统是否安全最重要的因素也是人。顾基发提出的“物事人”的系统方法论，用来分析安全，则应该从“物事人”这三个方面认识安全。本章主要讲作为人，应到了解的安全方法和理念。

## 安全常识

### 物理防护

说到物理防护，就是不能让别人把我们的网给剪断了，电脑给搬走了。比如，

- 下班后办公室必须锁门；
- 张贴非授权人员不得入内等标语；
- 服务器机房安装视频监控和警报系统，只允许特定时间特定人员访问；
- Windows 电脑设置三层密码（BIOS、syskey、Windows三层密码），深度deepin可以设置两层密码（BIOS、Login两层密码）；
- 全部门设置同样的提醒安全的桌面和提醒安全的屏保；
- 自动屏保的时间不能过长，再次唤醒比如输入密码；
- 桌面上除了当前正在操作的文件，不允许存放其他任何文件；
- 每天工作结束，文件必须保存备份到服务器，设置为只读模式，不允许其他人擅自修改文件。

### 灾后恢复

虽然自己的电脑使用的是深度deepin系统，但是办公时，还必须是windows 7系统。win7蓝屏，中病毒的频率太高了，不能指望微软再维护该系统了，也不指望360能清除甚至预防病毒，更不指望单位给换台新电脑，只有立足自身，建立私有网盘（参见本书第\@ref(chap:ftp-server-intro:seafile)节），随时备份自己的文件，以应对随时可能的蓝屏和死机。当然深度系统，也不是不会出现灾难，万一你一不小心执行了一句`# rm -rf /`呢？一下子把系统整崩溃了。

对于灾难，重在预防。预防的思路大致如下。

- 哪些要备份？
- 备份在哪里？
- 要存档多久？
- 存盘怎么用？

根据重要性确定哪些资料要备份后，对于普通的文件可以备份三份到不同的地方。特别重要的文件可以多备份几份。以我单位为例，本地电脑上有一份存档，使用seafile服务器随时同步一份文档，在文件服务器上每天结束也备份了一个版本。每年对重要的数据，还会刻光盘存储，有效期十年。

备份的话，最好要有一个不在本地电脑上，比如某个服务器，或者多个服务器上，避免自己的电脑崩溃，啥东西都找不回来了。另外，也可以使用不同的操作系统的服务器，我办公使用的win7操作系统，文件服务器为Linux centos的，这样本地电脑的病毒，一般还不至于把服务器也给感染了。算是一种防护吧。

存档时间长短，根据实际需要吧。比如我单位每天晚上都要备份一次，部分同事嫌麻烦，私自决定每周备份一次。部门的规章制度要求重要数据每年备份一次，备份时间为十年。我觉得这个已经够长了。

对于存档，大家都懂得，不停的存，早晚把空间占满。就像行车记录仪，录像要时刻保持半个小时的内容，对于时间太长的旧内容就可以覆盖掉了。存盘（光盘除外）也一样，循环反复利用磁盘，就可以设定一下对于多长时间的资料可以删除了，给新的版本腾出空间。

常用的备份软件如下。

- 百度云盘？（打个广告）
- 自建云盘（比如seafile）
- amanda
- cpio
- dump/restore
- tar
- 系统删除后如何恢复文件？

关于这些软件的具体做法，后面补充。（**记得加入这部分内容**）

### 账号防护

基于权限的安全管理，离不开对账号的管理。合适的账号管理，有助于提高安全性，比如下面这几条建议：

- 单一原则，每个用户有且只有一个账号；
- 规范限制对超级账号root的使用；
- 对临时账号设置有效期；
- 删除停用账号。

#### 每个用户有且只有一个账号

我单位的网站建立在局域网内，外人无法访问。大家都喜欢使用超级管理员账号登录，而且密码就是简单的``123456``，谁都可以访问，谁都可以擅自修改数据，关键是你还找不到是哪个人干的。这么糟糕的状态还在持续，虽然提了建议，后来有所改变，还是有小部分人都知道超级管理员的密码，并且都是用他来访问网站。找不到谁干的这个问题，有多可怕，只是后果现在还没显示出来。作恶可追溯，且不能被否认，这是账户防护必须要考虑的问题。采用每个用户有且只有一个账号的策略能够较好的解决这个问题。

#### 规范限制对超级账号root的使用

限制超级账号root的使用，也是一个必须要考虑的问题。root账号的权限实在太大了，属于“绝对的权力”，所谓“绝对的权力产生绝对的腐败”，这样的权限安排，是存在风险的。当然从操作系统上更改这种权限设计，不是我们用户考虑的事情，我们可以做到的是，不能多人共同使用root帐号。通过`sudo`对权限细粒度的划分，并做好日志。关于`sudo`的更多介绍，参考第\@ref(chap:manager-user)章。Instead of giving multiple people root permission on a Linux system, you can grant root 
access on a per-command basis with the sudo command. Using sudo provides the following 
security benefi ts:
■ The root password does not have to be given out.
■ You can fi ne-tune command access.
■ All sudo use (who, what, when) is recorded in /var/log/secure.
All failed sudo access attempts are logged.
After you grant someone sudo permission, you can try to restrict root access to certain commands in the /etc/sudoers fi le (with the visudo command). However, after you grant root 
permission to a user, even in a limited way, it is diffi cult to be sure that a determined user 
can’t fi nd ways to gain full root access to your system and do what he or she wants to it.
One way to keep a misbehaving administrator in check is to have security messages 
intended for the /var/log/secure fi le sent to a remote log server that none of the local 
administrators have access to. In that way, any misuse of root privilege is attached to a 
particular user and is logged in a way that the user can’t cover his or her tracks.

#### 对账号设置有效期

电脑有时会被临时借用，这个时候最好设置个临时帐号，这帐号加上有效期。我单位使用的windows电脑，同事比较熟悉，都相互知道对方电脑的密码，就没有设置临时帐号的意识。通常的做法时，把电脑借出去，回来该密码。但是，如果我们的是服务器的话，我觉得，给他们设置一个临时帐号相对更安全些，避免临时人员分析出我们密码设置的习惯。给自己的帐号设置有效期，还算需要慎重，之前练习把自己的帐号就设置了一个有效期，过期后，就无法登录了。不得已，跑到`Ctrl+Alt+F2`虚拟终端里登录root帐号给改回来的。

但是，对全体人员的帐号进行时效控制，还是非常必要的安全手段。

```bash
$ usermod --help
用法：usermod [选项] 登录

选项：
  -e, --expiredate EXPIRE_DATE  设定帐户过期的日期为 EXPIRE_DATE
  -f, --inactive INACTIVE       过期 INACTIVE 天数后，设定密码为失效状态
```

比如设置，

```bash
# usermod -e 2020-12-31 bubifengyun
```

使用`chage`可以查看用户的时效等信息。比如，

```bash
$ chage -l bubifengyun
最近一次密码修改时间					：4月 20, 2020
密码过期时间					：从不
密码失效时间					：从不
帐户过期时间						：从不
两次改变密码之间相距的最小天数		：0
两次改变密码之间相距的最大天数		：99999
在密码过期之前警告的天数	：7
```

```{block2, note-text, type='rmdnote'}
注意，chage命令是通过*/etc/shadow*查询信息的。如果不存在该文件，则`chage`无法正常使用。
```

#### 删除停用帐号

离职人员还偷偷修改公司数据的新闻时常见诸报端，甚至还有删库的恶劣犯法行为。对离职人员，进行脱密教育的同时，在公司内部采用必要的安全防范措施，也是一个很值得考虑的问题。及时删除停用帐号就是一个比较好的安全防范措施。

通常采用如下几步删除停用帐号，

1. 查找该帐号所有文件资料，`find / -user <待删除帐号>`;
1. 禁用该帐号，并停止其有效期;
1. 备份该帐号的这些文件;
1. 删除这些文件，或者修改这些文件的拥有者;
1. 删除该帐号;

**注意：**步骤顺序，应当先禁用或者停用该帐号，然后再操作其他步骤，避免趁这个空隙，该帐号又创建了其他文件或者做了不该做的事情。

### 密码防护

**不要使用简单易猜密码。**比如姓名、电话号码、单位名称、网址；或者有序的数字、字母，键盘上类似“qwerty”的连续按键。可以着手从一下几个方面改善密码，

- 增加长度，这个是最粗暴有效的手段；
- 增加不同的字符，比如大小写字母数字和`“~!@#$”`等特殊字符；
- 如果支持汉字，不妨加入汉字密码。

除此之外，12306网站提供的那些动态的汉字验证码以及图片验证，也是比较好的安全手段，当然这个图片验证码吐槽也是比较多的。

不过密码还是需要人来记忆的，搞得太复杂，自己都忘了，或者写在纸上，则得不偿失了。尽量选择一些有意义的密码，长度够，也容易记。

如果要修改密码，可以使用如下命令。

```bash
$ passwd <用户名>
```

这里是修改自己的密码，需要输入当前密码。输入密码时，密码不会显示在屏幕上。如果使用root用户，不管是修改root还是其他用户的密码，都不需要输入当前密码。下面是用户 bubifengyun 修改自己的密码，如果修改自己的密码，`passwd`后的用户名是可以省略的。

```bash
$ passwd bubifengyun 
为 bubifengyun 更改 STRESS 密码。
Current password: 
新的 密码：
重新输入新的 密码：
```

为了更好的提高密码安全性，还可以在制度上下功夫，比如要求企业内部的密码必须满足特定的要求，定期更换密码，不得使用之前用过的密码，对人员进行保密教育，拿低劣的密码做警示教育。

但是制度是好的，能不能坚持下来则另当别论。为了更好的坚持制度，还可以在技术上强制执行这些规定。比如配置登录相关的文件*/etc/login.defs*，该文件在第\@ref(chap:manager-user)章详细介绍，主要内容如下。

```{block2}
#
# /etc/login.defs - Configuration control definitions for the login package.
#
# Three items must be defined:  MAIL_DIR, ENV_SUPATH, and ENV_PATH.
# If unspecified, some arbitrary (and possibly incorrect) value will
# be assumed.  All other items are optional - if not specified then
# the described action or option will be inhibited.
#
# Comment lines (lines beginning with "#") and blank lines are ignored.
#
# Modified for Linux.  --marekm

# REQUIRED for useradd/userdel/usermod
#   Directory where mailboxes reside, _or_ name of file, relative to the
#   home directory.  If you _do_ define MAIL_DIR and MAIL_FILE,
#   MAIL_DIR takes precedence.
#
#   Essentially:
#      - MAIL_DIR defines the location of users mail spool files
#        (for mbox use) by appending the username to MAIL_DIR as defined
#        below.
#      - MAIL_FILE defines the location of the users mail spool files as the
#        fully-qualified filename obtained by prepending the user home
#        directory before $MAIL_FILE
#
# NOTE: This is no more used for setting up users MAIL environment variable
#       which is, starting from shadow 4.0.12-1 in Debian, entirely the
#       job of the pam_mail PAM modules
#       See default PAM configuration files provided for
#       login, su, etc.
#
# This is a temporary situation: setting these variables will soon
# move to /etc/default/useradd and the variables will then be
# no more supported
MAIL_DIR        /var/mail
#MAIL_FILE      .mail

#
# Enable logging and display of /var/log/faillog login failure info.
# This option conflicts with the pam_tally PAM module.
#
FAILLOG_ENAB		yes

#
# Enable display of unknown usernames when login failures are recorded.
#
# WARNING: Unknown usernames may become world readable. 
# See #290803 and #298773 for details about how this could become a security
# concern
LOG_UNKFAIL_ENAB	no

#
# Enable logging of successful logins
#
LOG_OK_LOGINS		no

#
# Enable "syslog" logging of su activity - in addition to sulog file logging.
# SYSLOG_SG_ENAB does the same for newgrp and sg.
#
SYSLOG_SU_ENAB		yes
SYSLOG_SG_ENAB		yes

#
# If defined, all su activity is logged to this file.
#
#SULOG_FILE	/var/log/sulog

#
# If defined, file which maps tty line to TERM environment parameter.
# Each line of the file is in a format something like "vt100  tty01".
#
#TTYTYPE_FILE	/etc/ttytype

#
# If defined, login failures will be logged here in a utmp format
# last, when invoked as lastb, will read /var/log/btmp, so...
#
FTMP_FILE	/var/log/btmp

#
# If defined, the command name to display when running "su -".  For
# example, if this is defined as "su" then a "ps" will display the
# command is "-su".  If not defined, then "ps" would display the
# name of the shell actually being run, e.g. something like "-sh".
#
SU_NAME		su

#
# If defined, file which inhibits all the usual chatter during the login
# sequence.  If a full pathname, then hushed mode will be enabled if the
# user's name or shell are found in the file.  If not a full pathname, then
# hushed mode will be enabled if the file exists in the user's home directory.
#
HUSHLOGIN_FILE	.hushlogin
#HUSHLOGIN_FILE	/etc/hushlogins

#
# *REQUIRED*  The default PATH settings, for superuser and normal users.
#
# (they are minimal, add the rest in the shell startup files)
ENV_SUPATH	PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV_PATH	PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

#
# Terminal permissions
#
#	TTYGROUP	Login tty will be assigned this group ownership.
#	TTYPERM		Login tty will be set to this permission.
#
# If you have a "write" program which is "setgid" to a special group
# which owns the terminals, define TTYGROUP to the group number and
# TTYPERM to 0620.  Otherwise leave TTYGROUP commented out and assign
# TTYPERM to either 622 or 600.
#
# In Debian /usr/bin/bsd-write or similar programs are setgid tty
# However, the default and recommended value for TTYPERM is still 0600
# to not allow anyone to write to anyone else console or terminal

# Users can still allow other people to write them by issuing 
# the "mesg y" command.

TTYGROUP	tty
TTYPERM		0600

#
# Login configuration initializations:
#
#	ERASECHAR	Terminal ERASE character ('\010' = backspace).
#	KILLCHAR	Terminal KILL character ('\025' = CTRL/U).
#	UMASK		Default "umask" value.
#
# The ERASECHAR and KILLCHAR are used only on System V machines.
# 
# UMASK is the default umask value for pam_umask and is used by
# useradd and newusers to set the mode of the new home directories.
# 022 is the "historical" value in Debian for UMASK
# 027, or even 077, could be considered better for privacy
# There is no One True Answer here : each sysadmin must make up his/her
# mind.
#
# If USERGROUPS_ENAB is set to "yes", that will modify this UMASK default value
# for private user groups, i. e. the uid is the same as gid, and username is
# the same as the primary group name: for these, the user permissions will be
# used as group permissions, e. g. 022 will become 002.
#
# Prefix these values with "0" to get octal, "0x" to get hexadecimal.
#
ERASECHAR	0177
KILLCHAR	025
UMASK		022

#
# Password aging controls:
#
#	PASS_MAX_DAYS	Maximum number of days a password may be used.
#	PASS_MIN_DAYS	Minimum number of days allowed between password changes.
#	PASS_WARN_AGE	Number of days warning given before a password expires.
#
PASS_MAX_DAYS	99999
PASS_MIN_DAYS	0
PASS_WARN_AGE	7

#
# Min/max values for automatic uid selection in useradd
#
UID_MIN			 1000
UID_MAX			60000
# System accounts
#SYS_UID_MIN		  100
#SYS_UID_MAX		  999

#
# Min/max values for automatic gid selection in groupadd
#
GID_MIN			 1000
GID_MAX			60000
# System accounts
#SYS_GID_MIN		  100
#SYS_GID_MAX		  999

#
# Max number of login retries if password is bad. This will most likely be
# overriden by PAM, since the default pam_unix module has it's own built
# in of 3 retries. However, this is a safe fallback in case you are using
# an authentication module that does not enforce PAM_MAXTRIES.
#
LOGIN_RETRIES		5

#
# Max time in seconds for login
#
LOGIN_TIMEOUT		60

#
# Which fields may be changed by regular users using chfn - use
# any combination of letters "frwh" (full name, room number, work
# phone, home phone).  If not defined, no changes are allowed.
# For backward compatibility, "yes" = "rwh" and "no" = "frwh".
# 
CHFN_RESTRICT		rwh

#
# Should login be allowed if we can't cd to the home directory?
# Default in no.
#
DEFAULT_HOME	yes

#
# If defined, this command is run when removing a user.
# It should remove any at/cron/print jobs etc. owned by
# the user to be removed (passed as the first argument).
#
#USERDEL_CMD	/usr/sbin/userdel_local

#
# If set to yes, userdel will remove the user's group if it contains no
# more members, and useradd will create by default a group with the name
# of the user.
#
# Other former uses of this variable such as setting the umask when
# user==primary group are not used in PAM environments, such as Debian
#
USERGROUPS_ENAB yes

#
# Instead of the real user shell, the program specified by this parameter
# will be launched, although its visible name (argv[0]) will be the shell's.
# The program may do whatever it wants (logging, additional authentification,
# banner, ...) before running the actual shell.
#
# FAKE_SHELL /bin/fakeshell

#
# If defined, either full pathname of a file containing device names or
# a ":" delimited list of device names.  Root logins will be allowed only
# upon these devices.
#
# This variable is used by login and su.
#
#CONSOLE	/etc/consoles
#CONSOLE	console:tty01:tty02:tty03:tty04

#
# List of groups to add to the user's supplementary group set
# when logging in on the console (as determined by the CONSOLE
# setting).  Default is none.
#
# Use with caution - it is possible for users to gain permanent
# access to these groups, even when not logged in on the console.
# How to do it is left as an exercise for the reader...
#
# This variable is used by login and su.
#
#CONSOLE_GROUPS		floppy:audio:cdrom

#
# If set to "yes", new passwords will be encrypted using the MD5-based
# algorithm compatible with the one used by recent releases of FreeBSD.
# It supports passwords of unlimited length and longer salt strings.
# Set to "no" if you need to copy encrypted passwords to other systems
# which don't understand the new algorithm.  Default is "no".
#
# This variable is deprecated. You should use ENCRYPT_METHOD.
#
#MD5_CRYPT_ENAB	no

#
# If set to MD5 , MD5-based algorithm will be used for encrypting password
# If set to SHA256, SHA256-based algorithm will be used for encrypting password
# If set to SHA512, SHA512-based algorithm will be used for encrypting password
# If set to DES, DES-based algorithm will be used for encrypting password (default)
# Overrides the MD5_CRYPT_ENAB option
#
# Note: It is recommended to use a value consistent with
# the PAM modules configuration.
#
ENCRYPT_METHOD SHA512

#
# Only used if ENCRYPT_METHOD is set to SHA256 or SHA512.
#
# Define the number of SHA rounds.
# With a lot of rounds, it is more difficult to brute forcing the password.
# But note also that it more CPU resources will be needed to authenticate
# users.
#
# If not specified, the libc will choose the default number of rounds (5000).
# The values must be inside the 1000-999999999 range.
# If only one of the MIN or MAX values is set, then this value will be used.
# If MIN > MAX, the highest value will be used.
#
# SHA_CRYPT_MIN_ROUNDS 5000
# SHA_CRYPT_MAX_ROUNDS 5000

################# OBSOLETED BY PAM ##############
#						#
# These options are now handled by PAM. Please	#
# edit the appropriate file in /etc/pam.d/ to	#
# enable the equivelants of them.
#
###############

#MOTD_FILE
#DIALUPS_CHECK_ENAB
#LASTLOG_ENAB
#MAIL_CHECK_ENAB
#OBSCURE_CHECKS_ENAB
#PORTTIME_CHECKS_ENAB
#SU_WHEEL_ONLY
#CRACKLIB_DICTPATH
#PASS_CHANGE_TRIES
#PASS_ALWAYS_WARN
#ENVIRON_FILE
#NOLOGINS_FILE
#ISSUE_FILE
#PASS_MIN_LEN
#PASS_MAX_LEN
#ULIMIT
#ENV_HZ
#CHFN_AUTH
#CHSH_AUTH
#FAIL_DELAY

################# OBSOLETED #######################
#						  #
# These options are no more handled by shadow.    #
#                                                 #
# Shadow utilities will display a warning if they #
# still appear.                                   #
#                                                 #
###################################################

# CLOSE_SESSIONS
# LOGIN_STRING
# NO_PASSWORD_CONSOLE
# QMAIL_DIR
```

使用 `chage` 


### 文件系统的防护

### 软件和服务管理

### 高级设置

## 监控系统

### 监控日志

### 监控账号

### 监控文件系统

## 系统的审计和复盘 