#  流程图绘制 {#diagram}


试着画个流程图
```{r echo=FALSE}

library(shape)
library(diagram)
par(mar = c(1, 1, 1, 1), mfrow = c(2, 2))
 #
 #
 names <- c("A", "B", "C", "D")
 M <- matrix(nrow = 4, ncol = 4, byrow = TRUE, data = 0)
 plotmat(M, pos = c(1, 2, 1), name = names, lwd = 1,
 box.lwd = 2, cex.txt = 0.8, box.size = 0.1,
 box.type = "square", box.prop = 0.5)
 #
 M[2, 1] <- M[3, 1] <- M[4, 2] <- M[4, 3] <- "flow"
 plotmat(M, pos = c(1, 2, 1), curve = 0, name = names, lwd = 1,
 box.lwd = 2, cex.txt = 0.8, box.type = "circle", box.prop = 1.0)
 #
 #
 diag(M) <- "self"
 plotmat(M, pos = c(2, 2), curve = 0, name = names, lwd = 1, box.lwd = 2,
 cex.txt = 0.8, self.cex = 0.5, self.shiftx = c(-0.1, 0.1, -0.1, 0.1),
 box.type = "diamond", box.prop = 0.5)
 M <- matrix(nrow = 4, ncol = 4, data = 0)
 M[2, 1] <- 1 ; M[4, 2] <- 2 ; M[3, 4] <- 3 ; M[1, 3] <- 4
 Col <- M
 Col[] <- "black"
 Col[4, 2] <- "darkred"
 pp <- plotmat(M, pos = c(1, 2, 1), curve = 0.2, name = names, lwd = 1,
 box.lwd = 2, cex.txt = 0.8, arr.type = "triangle",
 box.size = 0.1, box.type = "hexa", box.prop = 0.25,
 arr.col = Col, arr.len = 1)
 mtext(outer = TRUE, side = 3, line = -1.5, cex = 1.5, "plotmat")
 #
 par(mfrow = c(1, 1))
```


修改一个流程图

```{r echo=FALSE}
par(mar = c(1, 1, 1, 1))
openplotmat(main = "箭头表示")
elpos <- coordinates (c(1, 2, 1), mx = 0.1, my = -0.1)
curvedarrow(from = elpos[1, ], to = elpos[2, ], curve = -0.5, lty = 2, lcol = 2)
straightarrow(from = elpos[1, ], to = elpos[2, ], lty = 3, lcol = 3)
segmentarrow (from = elpos[1, ], to = elpos[2, ], lty = 1, lcol = 1)
treearrow (from = elpos[2:3, ], to = elpos[4, ], lty = 4, lcol = 4)
bentarrow (from = elpos[3, ], to = elpos[3, ]-c(0.1, 0.1),arr.pos=1,lty=5,lcol=5)
bentarrow(from = elpos[1, ], to = elpos[3, ], lty = 5, lcol = 5)
selfarrow(pos = elpos[3, ], path = "R",lty = 6, curve = 0.075, lcol = 6)
splitarrow(from = elpos[1, ], to = elpos[2:3, ], lty = 1, lwd = 1, dd = 0.7, arr.side = 1:2, lcol = 7)
for ( i in 1:4){
  textrect (elpos[i, ], 0.05, 0.05, lab = i, cex = 1.5)
}
legend("topright", lty = 1:7, legend = c("segmentarrow","curvedarrow", "straightarrow", "treearrow", "bentarrow",
                                         "selfarrow", "splitarrow"), lwd = c(rep(2, 6), 1), col = 1:7)
```

```{r echo=FALSE}
openplotmat(main="segmentarrow")

pos <-cbind(A <- seq(0.2, 0.8, by = 0.2), rev(A))

text(pos, LETTERS[1:4], cex = 2)

segmentarrow(from = pos[1, ] + c(0, 0.05), to = pos[2, ] + c(0, 0.05),
             arr.pos = 1, arr.adj = 1, dd = 0.1, 
             path = "UHD", lcol = "darkred")

segmentarrow(from = pos[2, ] + c(-0.05, 0), to = pos[3, ] + c(-0.05, 0.01),
             arr.pos = 1, arr.adj = 1, dd = 0.1,
             lcol = "black", arr.type = "triangle")

segmentarrow(from = pos[2, ] + c(0.05, 0), to = pos[3, ] + c(0.05, 0.01),
             arr.pos = 0.5, dd = 0.3, path = "RVL", arr.side = 1,
             lcol = "lightblue", arr.type = "simple")  

segmentarrow(from = pos[3, ] + c(0.05, 0), to = pos[4, ] + c(-0.05, 0.01),
             arr.pos = 0.5, dd = 0.05, path = "RVL", lcol = "darkblue",
             arr.type = "ellipse")  

segmentarrow(from = pos[3, ] + c(0, -0.05), to = pos[4, ] + c(0, 0.05),
             arr.pos = 0.5, arr.side = 3, dd = 0.05, path = "DHU",
             lcol = "darkgreen")  

segmentarrow(from = pos[3,] + c(-0.05, -0.05), to = pos[4, ] + c(0, -0.05),
             arr.pos = 0.5, arr.side = 1:3, dd = 0.3, path = "DHU",
             lcol = "green")

```

我们首先确定有多少个框，比如6个，最开始是启动框。让他们无连线。
放在5行3列的矩阵里。行间距 0.2，列间距 0.3。总长度均为1.

```{r echo=FALSE}
openplotmat(main="流程图六个")

rx <- 0.1
ry <- 0.05

pos <-cbind(c(0.3,0.3,0.6,0.9,0.9,0.9),c(0.9,0.7,0.5,0.5,0.3,0.1))

M <- matrix(nrow=6,ncol=6,byrow = TRUE,data=0);
names <-c("开始","进度一","分支","进度二","进度三","结束")

textround(mid=pos[1,], radx=rx, rady = ry, la= names[1], cex=1.5, shadow.size = 0)

textrect(mid=pos[2,], radx=rx, rady = ry, la= names[2], cex=1.5, shadow.size = 0)
textdiamond(mid=pos[3,], radx=rx, rady = ry, la= names[3], cex=1.5, shadow.size = 0)
for(i in 4:5) {
  textrect(mid=pos[i,], radx=rx, rady = ry, la= names[i], cex=1.5, shadow.size = 0)
}
textellipse(mid=pos[6,], radx=rx, rady = ry, la= names[6], cex=1.5, shadow.size = 0)

```


下面考虑划线，各种箭头。

```{r echo=FALSE}

openplotmat(main="流程图六个")

rx <- 0.1
ry <- 0.05

pos <-cbind(c(0.3,0.3,0.6,0.9,0.9,0.9),c(0.9,0.7,0.5,0.5,0.3,0.1))

M <- matrix(nrow=6,ncol=6,byrow = TRUE,data=0);
names <-c("开始","进度一","分支","进度二","进度三","结束")

textround(mid=pos[1,], radx=rx, rady = ry, la= names[1], cex=1.5, shadow.size = 0)

textrect(mid=pos[2,], radx=rx, rady = ry, la= names[2], cex=1.5, shadow.size = 0)
textdiamond(mid=pos[3,], radx=rx, rady = ry, la= names[3], cex=1.5, shadow.size = 0)
for(i in 4:5) {
  textrect(mid=pos[i,], radx=rx, rady = ry, la= names[i], cex=1.5, shadow.size = 0)
}
textellipse(mid=pos[6,], radx=rx, rady = ry, la= names[6], cex=1.5, shadow.size = 0)

# draw line

dh <- c(0.1,0)
dv <- c(0,0.05)
straightarrow(from = pos[1, ] - dv, to = pos[2, ]+ dv, lty = 1, arr.type = "triangle")

segmentarrow(from = pos[2, ]+c(0,-0.05), to = pos[3, ] + c(0, 0.05),
             arr.pos = 0.5, arr.side = 3, dd = 0.05,
             path="DHU", arr.type = "triangle")

dev.off();
```
